header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - 'docs'
    - 'bitsail-dist'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '**/*.json'
    - '**/*.iml'
    - '**/.gitignore'
    - '**/*.yml'
    - '**/*.yaml'
    - 'build.sh'
    - 'bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hudi/src/test/resources/'
    - 'bitsail-base/src/test/resources/'

  comment: on-failure