use TEST;

create table ORACLE_DYNAMIC_TABLE
(
    ID          VARCHAR2(1024),
    DATETIME    NUMBER,
    INT_TYPE    NUMBER,
    BIGINT_TYPE NUMBER,
    FLOAT_TYPE  NUMBER,
    DOUBLE_TYPE NUMBER,
    RAW_TYPE    RAW(1024),
    DATE_TYPE   DATE
)