name: 'ðŸ› Bug Report'
title: '[Bug][XxxType] Description'
description: Problems and issues with code of BitSail
body:
  - type: markdown
    attributes:
      value: |
        Thank you for finding the time to report the problem! We really appreciate the community efforts to improve BitSail.

        Please explain your issue precisely, and if possible provide a reproducer snippet (this helps resolve issues much quicker).

  - type: textarea
    attributes:
      label: What happened
      description: Describe what happened.
      placeholder: >
        Please provide the context in which the problem occurred and explain what happened.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What do you expect to happen
      description: What do you think went wrong?
      placeholder: >
        Please explain why you think the behavior is erroneous.

        It is extremely helpful if you copy and paste the fragment of logs showing the exact error messages
        or wrong behavior and screenshots for UI problems.

        You can include files by dragging and dropping them here.
    validations:
      required: false

  - type: textarea
    attributes:
      label: How to reproduce
      description: >
        What should we do to reproduce the problem?

        Please add the following content as appropriate and use screenshots if necessary.

        1. The job conf is: '....'

        2. The test data is: '....'

        3. BitSail run command: '....'

        4. ...
      placeholder: >
        Please make sure you provide a reproducible step-by-step case of how to reproduce the problem
        as precisely as possible. Remember that non-reproducible issues will be closed!

        Keep in mind we do not have access to your deployment.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Build Environment
      description: >
        In which environment did you build the project?

        Not required if you download from our [Releases](https://github.com/bytedance/bitsail/releases).
      placeholder: >
        - Download from releases

        - OS [e.g. macOS Big Sur Version 11.3.1]

        - JDK [e.g. 1.8.0_301]

        - Maven [e.g. 3.6.3]

        - ...

  - type: textarea
    attributes:
      label: Execution Environment
      description: >
        In which environment did you run the project?
      placeholder: >
        - OS [e.g. macOS Big Sur Version 11.3.1]

        - JDK [e.g. 1.8.0_301]

        - Deployment [e.g. Yarn | CDH 6.3.x]

        - ...

  - type: dropdown
    attributes:
      label: BitSail version
      description: |
        Which version of BitSail are you using?
      multiple: false
      options:
        - 'master'
        - '0.1.0'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: BitSail Component or Code Module
      description: |
        Which component or code module of BitSail did you find the bug from?
      multiple: true
      options:
        - 'BitSail Doc'
        - 'BitSail Pom'
        - 'BitSail Core'
        - 'BitSail Test'
        - 'BitSail Component'
        - 'BitSail Connector'
        - 'Other for not specified type'
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
      options:
        - label: Yes, I am willing to submit a PR!

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >
            I agree to follow this project's
            [Code of Conduct](https://github.com/bytedance/bitsail/blob/master/CODE_OF_CONDUCT.md)
          required: true

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
